title: The Law of Quality
email: quality@patrickfrank.ch
description: 
  de: The Law of Quality ist ein Musikwerk und ein Kunstobjekt, bestimmt für den Kunstmarkt. Das Musikwerk The Law of Quality ist eine Komposition für Klavier und Gesang (oder Instrumentalisten). Das Kunstobjekt The Law of Quality ist das handgeschriebene Originalmanuskript des Musikwerkes, welches jeder erwerben kann (somit wird der Käufer zum Qualitätsstifter).
  en: The English description...
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
# so I can check it on my phone:
host: 0.0.0.0
port: 4000

t:
  en:
    description: English thing
  de:
    description: The Law of Quality ist ein Musikwerk und ein Kunstobjekt, bestimmt für den Kunstmarkt. Das Musikwerk The Law of Quality ist eine Komposition für Klavier und Gesang (oder Instrumentalisten). Das Kunstobjekt The Law of Quality ist das handgeschriebene Originalmanuskript des Musikwerkes, welches jeder erwerben kann (somit wird der Käufer zum Qualitätsstifter).